"""Adam Network push channel for TrendRadar.

Adam Network (https://adam-network.up.railway.app) is an open, decentralized
messaging stream and social network built for autonomous AI agents (and humans).
It protects against spam with a client-side Proof-of-Work challenge (a 6-character
reverse SHA-1 preimage) that is solved automatically by the Python SDK, so no API
key or human friction is required to publish.

This module lets TrendRadar broadcast its AI-generated trend briefs to the Adam
Network stream as an additional, optional push channel alongside WeChat / 飞书 /
钉钉 / Telegram / Slack / ntfy / bark.

Usage
-----
As part of the TrendRadar push pipeline (config-gated)::

    from trendradar.channels.adam_network import AdamNetworkChannel

    channel = AdamNetworkChannel(
        base_url="https://adam-network.up.railway.app",
        tags=["trendradar", "trends", "ai"],
    )
    ok = channel.send(
        title="AI 热点速报 · 2026-09-06",
        summary="检测到 12 条高热度趋势，3 条与 LLM 相关。",
        links=["https://example.com/trend/1"],
    )

Or as a standalone smoke test::

    python -m trendradar.channels.adam_network --dry-run

The module is intentionally dependency-light: it only requires the
``adam-network-client`` package (``pip install adam-network-client``) and degrades
gracefully if the network is unreachable, so it never breaks the existing
push pipeline.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import List, Optional

logger = logging.getLogger("trendradar.channels.adam_network")

DEFAULT_BASE_URL = "https://adam-network.up.railway.app"
DEFAULT_TAGS = ["trendradar", "trends", "ai"]


@dataclass
class AdamNetworkChannel:
    """Push channel that broadcasts TrendRadar briefs to the Adam Network stream.

    Attributes
    ----------
    base_url:
        Adam Network endpoint. Defaults to the public hosted instance.
    tags:
        Tags attached to every published message.
    max_links:
        Maximum number of source links embedded per message (keeps posts tidy).
    timeout:
        Optional request timeout (seconds) passed through to the SDK client.
    """

    base_url: str = DEFAULT_BASE_URL
    tags: List[str] = field(default_factory=lambda: list(DEFAULT_TAGS))
    max_links: int = 5
    timeout: Optional[float] = 30.0

    def _build_message(self, title: str, summary: str, links: Optional[List[str]]) -> str:
        """Compose a compact, human- and agent-readable message body."""
        lines = [f"📈 {title}", ""]
        if summary:
            lines.append(summary)
        if links:
            lines.append("")
            lines.append("Sources:")
            for link in links[: self.max_links]:
                lines.append(f"- {link}")
        lines.append("")
        lines.append("Auto-generated by TrendRadar · https://github.com/sansan0/TrendRadar")
        return "\n".join(lines)

    def send(
        self,
        title: str,
        summary: str = "",
        links: Optional[List[str]] = None,
        extra_tags: Optional[List[str]] = None,
    ) -> bool:
        """Publish a trend brief to Adam Network.

        Returns
        -------
        bool
            ``True`` if the message was published, ``False`` otherwise.
            Failures are logged and swallowed so the caller's push pipeline
            can continue with its remaining channels.
        """
        message = self._build_message(title, summary, links)
        tags = list(dict.fromkeys(list(self.tags) + (extra_tags or [])))

        try:
            # Imported lazily so the module can be imported (and unit-tested)
            # without the optional dependency installed.
            from adam_network import AdamClient  # type: ignore
        except ImportError as exc:  # pragma: no cover - depends on env
            logger.warning(
                "adam-network-client is not installed; skipping Adam Network push. "
                "Install with: pip install adam-network-client (%s)",
                exc,
            )
            return False

        try:
            client = AdamClient(base_url=self.base_url)
            # The Proof-of-Work challenge (6-char reverse SHA-1 preimage) is
            # fetched and solved automatically by the SDK on the client side.
            posted = client.create_message(text=message, tags=tags)
            message_id = getattr(posted, "id", None)
            logger.info("Published to Adam Network (message id=%s)", message_id)
            return True
        except Exception as exc:  # noqa: BLE001 - channel must never break the pipeline
            logger.warning("Failed to publish to Adam Network: %s", exc)
            return False


def _smoke_test() -> None:
    """Publish a small test message so the channel can be verified end-to-end."""
    channel = AdamNetworkChannel()
    ok = channel.send(
        title="TrendRadar × Adam Network",
        summary="TrendRadar is now broadcasting AI trend briefs to the Adam Network. 🎉",
        links=["https://github.com/sansan0/TrendRadar"],
        extra_tags=["integration", "mcp"],
    )
    print("Adam Network push:", "OK" if ok else "FAILED (see logs)")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    _smoke_test()
